projetos/orquestra/cadastros/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('historia/', views.historia, name = 'historia'),
    path('musicos/', views.musicos, name = 'musicos'),
    path('diretoria/', views.diretoria, name = 'diretoria'),
    path('', views.index, name = 'galeria'),
    path('', views.index, name = 'agenda'),
    path('', views.index, name = 'contato'),
    path('cadastrar_diretoria/', views.cadastrar_diretoria, name="cadastrar_diretoria"),
    path('cadastros/', views.home, name='home'),
    path('cadastros/musicos/', views.listar_musicos, name='listar_musicos'),
    path('cadastros/musicos/adicionar/', views.cadastrar_musico, name='adicionar_musico'),
    path('cadastros/musicos/alterar/<int:id>/', views.alterar_musico, name='alterar_musico'),
    path('cadastros/musicos/excluir/<int:id>/', views.excluir_musico, name='excluir_musico'),
    path('cadastros/usuarios/', views.cadastrar_usuario, name='cadastrar_usuario'),
]

projetos/orquestra/orquestra/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cadastros.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

projetos/orquestra/cadastros/models.py
from django.db import models

# Create your models here.
class Naipe(models.Model):
    nome = models.CharField(max_length=20)

    def __str__(self):
        return self.nome
    
class Instrumento(models.Model):
    nome = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.nome}"
    
class Musico(models.Model):
    VOZES = {
        '1a': 'Primeira Voz',
        '2a': 'Segunda Voz',
        '3a': 'Terceira Voz',
    }
    codigo = models.AutoField(primary_key=True)
    nome = models.CharField('nome do músico', max_length=100)
    data_nascimento = models.DateField(verbose_name='data de nascimento')
    data_ingresso = models.DateField(verbose_name='data de ingresso')
    naipe = models.ForeignKey(Naipe, on_delete=models.CASCADE)
    instrumento = models.ForeignKey(Instrumento, on_delete=models.CASCADE, verbose_name='instrumento do músico')
    voz = models.CharField("voz do instrumento", max_length=2, choices=VOZES.items())
    foto = models.ImageField(upload_to='img/musicos', null=True, blank=True)
    

    def __str__(self):
        return f"{self.nome}"
    
class Diretoria(models.Model):
    CARGOS = [
        ('PRES', 'Presidente'),
        ('VP', 'Vice-presidente'),
        ('TES', 'Tesoureiro'),
        ('VT', 'Vice-tesoureiro'),
        ('SEC', 'Secretário'),
        ('2SEC', 'Segundo secretário')
    ]

    cargo = models.CharField(max_length=4, choices=CARGOS)
    nome = models.CharField(max_length=100)
    contato = models.EmailField(null=True, blank=True)

projetos/orquestra/cadastros/forms.py
from .models import Diretoria, Musico
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class DiretoriaForm(forms.ModelForm):
    class Meta:
        model = Diretoria
        fields = ['cargo', 'nome', 'contato']

class MusicoForm(forms.ModelForm):
    class Meta:
        model = Musico
        fields = '__all__'

class UsuarioForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

projetos/orquestra/cadastros/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.db.models import Prefetch
from .models import Diretoria, Naipe, Musico
from .forms import DiretoriaForm, MusicoForm, UsuarioForm

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Group
from django.contrib import messages

def index (request):
    return render(request, 'index.html', {'nome' : 'Fazendo Música'})

def historia(request):
    return render(request, 'historia.html', {'nome' : 'Fazendo Música'})

def musicos(request):
    # naipes = Naipe.objects.prefetch_related('musico_set').all().order_by('nome')
    musicos_ordenados = Musico.objects.order_by('nome')
    naipes = Naipe.objects.prefetch_related(Prefetch('musico_set', queryset = musicos_ordenados)).order_by('nome')
    return render(request, 'musicos.html', {'nome' : 'Fazendo Música', 'naipes' : naipes})

def diretoria(request):

    #componentes = [{'cargo' : 'Presidente', 'nome' : 'Presidente da Orquestra', 'contato' : 'pres@orquestra.com'},
    #               {'cargo' : 'Tesoureiro', 'nome' : 'Tesoureiro da Orquestra', 'contato' : 'tesou@orquestra.com'},
    #               {'cargo' : 'Secretario', 'nome' : 'Secretario da Orquestra', 'contato' : 'sec@orquestra.com'},
    #               ]
    componentes = Diretoria.objects.all()

    return render(request, 'diretoria.html', {'nome' : 'Fazendo Música', 'componentes' : componentes})

def cadastrar_diretoria(request):
    if request.method == 'POST':
        form = DiretoriaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('diretoria')
    else:
        form = DiretoriaForm()

    return render(request, 'cadastrar_diretoria.html', {'form': form })

# @permission_required('cadastro.view_musico', raise_exception=True)
def listar_musicos(request):
    musicos = Musico.objects.all()
    return render(request, 'cadastros/listar_musicos.html', {'musicos': musicos})

@permission_required('cadastro.add_musico', raise_exception=True)
def cadastrar_musico(request):
    if request.method == 'POST':
        form = MusicoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('listar_musicos')
    else:
        form = MusicoForm()
    return render(request, 'cadastros/forms_musicos.html', {'form': form})

@permission_required('cadastro.change_musico', raise_exception=True)
def alterar_musico(request, id):
    musico = get_object_or_404(Musico, codigo = id)
    if request.method == 'POST':
        form = MusicoForm(request.POST, request.FILES, instance=musico)
        if form.is_valid():
            form.save()
            return redirect('listar_musicos')
    else:
        form = MusicoForm(instance=musico)
    return render(request, 'cadastros/forms_musicos.html', {'form': form})

# @permission_required('cadastros.delete', raise_exception=True)
@login_required
def excluir_musico(request, id):

    if not request.user.has_perm('cadastros.delete_musico'):
        messages.error(request, 'Você não tem acesso à exclusão de músicos!')
        return redirect('listar_musicos')
    else:
        musico = get_object_or_404(Musico, codigo = id)
        musico.delete()
        return redirect('listar_musicos')

def home(request):
    return render(request, 'cadastros/home.html')

def cadastrar_usuario(request):
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            user = form.save()
            grupo = Group.objects.get(name = 'Cadastros')
            user.groups.add(grupo)
            return redirect('home')
    else:
        form = UsuarioForm()
    return render(request, 'cadastros/forms_usuario.html', {'form': form})

projetos/orquestra/cadastros/templates/base.html
<!DOCTYPE html>
<html lang="pt">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Site da Orquestra{% endblock %} </title>
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
</head>
<body>
    <header class="header">
        <img src="{% static 'img/logo.png' %}" alt="Orquestra Logo" class="logo">
        <nav>
            <div class="dropdown">
                <button><a href="{% url 'index' %}">Início</a></button>
            </div>
            <div class="dropdown">
                <button>Sobre</button>
                <div class="dropdown-content">
                    <a href="{% url 'historia' %}">História</a>
                    <a href="{% url 'musicos' %}">Músicos</a>
                    <a href="{% url 'diretoria' %}">Diretoria</a>
                </div>
            </div>
            <div class="dropdown">
                <button><a href="{% url 'agenda' %}">Agenda</a></button>
            </div>
            <div class="dropdown">
                <button><a href="{% url 'galeria' %}">Galeria</a></button>
            </div>
            <div class="dropdown">
                <button><a href="{% url 'contato' %}">Contato</a></button>
            </div>
        </nav>
    </header>
    <section class="main-content">
        {% block content %}

        {% endblock %}
    </section>
    <footer class="footer">
        <p>&copy; 2025 Orquestra. Todos os direitos reservados.</p>
        <p>Contato: contato@orquestra.br | Telefone: (00) 1234-5678 | @orquestra</p>
    </footer>
</body>
</html>

projetos/orquestra/cadastros/templates/base_cad.html
<!DOCTYPE html>
<html lang="pt">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Site da Orquestra{% endblock %} </title>
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
</head>
<body>
    <header class="header">
        <img src="{% static 'img/logo.png' %}" alt="Orquestra Logo" class="logo">
        {% if user.is_authenticated %}
            <p>Olá, {{ user.username }}!</p>
            <div class="dropdown">
                <button><a href="{% url 'home' %}">Home</a></button>
            </div>
            <div class="dropdown">
                <button><a href="{% url 'listar_musicos' %}">Músicos</a></button>
            </div>
            <div class="dropdown">
                <button><a href="{% url 'listar_musicos' %}">Cadastrar Usuário</a></button>
            </div>
            <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Sair</button>  
            </form>
        {% else %}
            <div class="dropdown">
                <button><a href="{% url 'login' %}">Logar</a></button>
            </div>
        {% endif %}
    </header>
    <section class="main-content">

        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        {% endif %}

        {% block content %}

        {% endblock %}
    </section>
    <footer class="footer">
        <p>&copy; 2025 Orquestra. Todos os direitos reservados.</p>
        <p>Contato: contato@orquestra.br | Telefone: (00) 1234-5678 | @orquestra</p>
    </footer>
</body>
</html>

projetos/orquestra/cadastros/templates/cadastrar_diretoria.html
<!DOCTYPE html>
<html>
    <head>
        <title>Cadastrar Diretoria</title>
    </head>
    <body>
        <h1>Novo Membro</h1>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Salvar</button>
        </form>
    </body>
</html>

projetos/orquestra/cadastros/templates/diretoria.html
{% extends 'base.html' %}

{% block title %}Diretoria da Orquestra {% endblock %}

{% block content %}

    <h2>Diretoria da Orquestra {{ nome }}</h2>

    <table class="tabela">
        <tr>
            <td>Cargo</td>
            <td>Nome</td>
            <td>Contato</td>
        </tr>
        
        {% for componente in componentes %}
        <tr>
            <td>{{ componente.get_cargo_display }}</td>
            <td>{{ componente.nome }}</td>
            <td>{{ componente.contato|default_if_none:"-"}}</td>
        </tr>       
        {% endfor %}

    </table>

{% endblock %}

projetos/orquestra/cadastros/templates/historia.html
{% extends 'base.html' %}

{% block title %}Orquestra Sinfônica - História{% endblock %}

{% block content %}
    <h2 style="font-size: 40px;">
        História da Orquestra Sinfônica {{ nome }}
    </h2>

    {% lorem %}
    
{% endblock %}

projetos/orquestra/cadastros/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Orquestra Sinfônica{% endblock %}

{% block content %}
    <h2 style="font-size: 40px;">
        Orquestra Sinfônica {{ nome }}
    </h2>
    <img src="{% static 'img/orquestra.jpg' %}" alt="Foto da Orquestra">
{% endblock %}

projetos/orquestra/cadastros/templates/musicos.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Orquestra Sinfônica - Músicos{% endblock %}

{% block content %}
    <h2 style="font-size: 40px;">
        Músicos da Orquestra Sinfônica {{ nome }}
    </h2>

    {% for naipe in naipes%}
    <div class="naipe">
        <h2>{{ naipe.nome }}</h2>
        <div class="musicos">
        {% for musico in naipe.musico_set.all %}
          <div class="musico">
            <img src="{% static musico.foto %}" alt="Foto do músico {{ musico.nome }}">
            <div class="nome">{{ musico.nome }}</div>
            <div class="instrumento">{{ musico.instrumento}} - {{ musico.get_voz_display }}</div>
          </div>
        {% endfor %}
        </div>
    </div>
    {% endfor %}
    
{% endblock %}